function [op_names] = showOptionNames()
%Function displays the optional input argument names for MCMC sampler
%   It will be helpful if you want to use setOptions() to set the values
%   corresponding to these names.
    op_names = {'seed','nloop','nwarmup','nexp_tmax','nexp_umax',...
             'Rev_Jump_t','Rev_Jump_u','tmin','umin',...
             'prob_mm1', 'prob_mm1_u','nbasis', 'sigmasqalpha',...
             'tau_prior_a', 'tau_prior_b','var_inflate','conv_diag',...
             'options','fname','batchsize','parcomp','disp_plots',...
             'disp_iter'};
end
